const path = require('node:path');
const FS = require('../lib/fs-wrapper');
const NewPackage = require('../lib/new-package');
const OsHelpers = require('../lib/os-helpers');

test('elm-tooling.json generated by new-package is up to date', async () => {
  // ...or at least equal to the one that this project uses
  const elmToolingJson = await FS.readJsonFile(
    path.resolve(OsHelpers.makePathOsAgnostic(__dirname), '../elm-tooling.json')
  );
  expect(NewPackage.elmToolingJson).toEqual(elmToolingJson);
});
